# Site Info
title:              "A Coder, a Programmer, a Hacker walk into Evan's Blog"
description: >
    首页描述首页描述首页描述首页描述首页描述首页描述首页描述
    首页描述首页描述首页描述。
keywords: >
    ok,cancel,wangjunneil,evan
google_analytics:   UA-XXXXXXX-X # Put your Google Analytics code


# Author Info
author_name:        "Evan's Blog"
author_email:       wangjunneil@gmail.com
author_gravatar:    evan.jpeg
github_username:    wangjunneil # GitHub username

# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
url:                "http://www.wangjunneil.com" 
permalink:          /:year/:month/:title/
timezone:           Asia/Shanghai

# Site Build
highlighter:        rouge
#markdown:           redcarpet
#redcarpet:
#    extensions:     ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data", "highlight", "footnotes"]
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "vendor", "Gemfile" ]
gems:
  - jekyll-sitemap

compress_html:
    clippings:      all
    ingore:
        envs:       [ "test" ]

defaults:
  -
    scope:
      path:         ""
    values:
      layout:       "null"
  -
    scope:
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      type:         "posts"
    values:
      layout:       "post"
      
gems: [jekyll-paginate]
paginate: 10
paginate_path: "/page/:num"
