#!/bin/bash

LOCAL_IP=`ifconfig -a|grep inet|grep -v 127.0.0.1|grep -v inet6|awk '{print $2}'|tr -d "addr:"`
sudo jekyll serve --ssl-cert ./ssl/localhost+2.pem --ssl-key ./ssl/localhost+2-key.pem --port 443 -H $LOCAL_IP 
